"""Generate the pure serving functions from their authoritative source definitions."""
from __future__ import annotations

import argparse
import ast
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "serving" / "_core.py"
SOURCES = {
    "s01_diagnose.py": ("POWER_COLS", "restore_hours", "build_datetime_index", "flag_and_repair",
                        "add_targets", "build_operating_calendar"),
    "s02_features.py": ("HOLIDAYS_2021", "FEATURE_LABELS", "_label", "add_calendar_features",
                        "SAFE_LAGS", "build_origin_frame", "add_lag_features", "add_origin_stats",
                        "add_production_weather_features", "FEATURE_GROUPS", "FEATURE_COLS", "build_features"),
    "s10_package.py": ("bundle_predict", "manifest_core_sha256"),
}


def generated_source():
    parts = ['# AUTO-GENERATED by tools/build_serving_core.py; edit src, then regenerate.\n',
             '"""Pure preprocessing, feature and prediction functions shared with training."""\n',
             'import hashlib\nimport json\n\nimport numpy as np\nimport pandas as pd\n']
    for filename, wanted in SOURCES.items():
        path = ROOT / "src" / filename
        text = path.read_text(encoding="utf-8")
        definitions = {}
        for node in ast.parse(text).body:
            if isinstance(node, ast.FunctionDef):
                definitions[node.name] = node
            elif isinstance(node, ast.Assign):
                definitions.update({target.id: node for target in node.targets if isinstance(target, ast.Name)})
            elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
                definitions[node.target.id] = node
        for name in wanted:
            if name not in definitions:
                raise ValueError(f"Missing {filename}:{name}")
            segment = ast.get_source_segment(text, definitions[name])
            digest = hashlib.sha256(segment.encode("utf-8")).hexdigest()[:12]
            parts.append(f"\n\n# {filename}::{name} sha256={digest}\n{segment}\n")
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generated_source()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != text:
            raise SystemExit("serving/_core.py is out of sync; run python tools/build_serving_core.py")
        print("SERVING_CORE_SYNC_OK")
    else:
        TARGET.write_text(text, encoding="utf-8")
        print("Generated serving/_core.py")


if __name__ == "__main__":
    main()
