# AUTO-GENERATED by tools/build_serving_core.py; edit src, then regenerate.
"""Pure preprocessing, feature and prediction functions shared with training."""
import hashlib
import json

import numpy as np
import pandas as pd


# s01_diagnose.py::POWER_COLS sha256=3a1580b0677a
POWER_COLS = ["15분", "30분", "45분", "60분"]


# s01_diagnose.py::restore_hours sha256=d376a0cd12e5
def restore_hours(df: pd.DataFrame) -> pd.DataFrame:
    """손상된 `시간` 값을 일자별 행 순서에 따라 0~23으로 복원한다.

    1.2절에서 기온으로 행 순서 보존을 검증했으므로 위치 기준 복원이 타당하다.
    두 날짜가 각각 정확히 24행이므로 `(날짜,시간)` 중복 5건도 동시에 해소된다.
    """
    out = df.copy()
    bad = (out["시간"] < 0) | (out["시간"] > 23)
    bad_dates = out.loc[bad, "날짜"].unique()
    for d in bad_dates:
        mask = out["날짜"] == d
        n = int(mask.sum())
        if n != 24:
            raise ValueError(f"{d}: 행 수가 24가 아님({n}) — 위치 기준 복원 불가")
        out.loc[mask, "시간"] = np.arange(n)
    return out


# s01_diagnose.py::build_datetime_index sha256=227713807cff
def build_datetime_index(df: pd.DataFrame) -> pd.DataFrame:
    """`날짜`·`시간` 으로 datetime 인덱스를 만든다."""
    out = df.copy()
    out["datetime"] = pd.to_datetime(out["날짜"], format="%Y%m%d") + pd.to_timedelta(
        out["시간"], unit="h"
    )
    out = out.sort_values("datetime").set_index("datetime")
    return out


# s01_diagnose.py::flag_and_repair sha256=e3e2255d498e
def flag_and_repair(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """결측을 표시하고 과거의 마지막 유효값으로만 대체한다.

    미래 관측값으로 역보간하지 않는다. 앞선 유효값이 없는 선두 결측은
    NaN으로 남겨 워밍업/서빙 입력 검증에서 제외하거나 거부한다.

    Returns
    -------
    (pandas.DataFrame, pandas.DataFrame)
        정비된 데이터프레임, 정비 로그.
    """
    out = df.copy()
    log = []

    # ── 센서측: 평균전력 0 = 계측 정지 ────────────────────────────────
    outage = out["평균"] == 0
    out["is_outage"] = outage
    log.append(("센서측 계측정지", int(outage.sum()), "과거 유효 전력 전방대체(ffill) + is_outage"))

    # ── ERP측 결측 vs 증강 채널 불일치 ────────────────────────────────
    # 생산량 0인데 전력이 정상 가동 수준인 날이 11일 있다. 둘은 원인이 다르다.
    #
    #  (a) ERP측 결측 (7/13·7/15) — `인건비`까지 손상되어 **전부 1.5**이고
    #      `시간` 컬럼도 손상됐다. 프로파일 복제그룹에 속하지 않는다(grp_size=1).
    #      → 실제 가동 중인데 ERP가 기록을 못 남긴 진짜 결측.
    #
    #  (b) 증강 채널 불일치 (9일) — 대부분 일요일·법정공휴일이고 `인건비`는
    #      정상(1.0/1.5 혼재)이다. 생산량·공장인원이 0인데 전력만 평일 수준이다.
    #      → **증강 과정에서 평일 전력 프로파일이 덮어씌워진** 것으로 판단한다.
    #        전력 채널만 복사되고 생산·달력 채널은 원본이 남은 **채널 불일치**다.
    daily_prod = out.groupby(out.index.normalize())["생산량"].transform("sum")
    daily_power = out.groupby(out.index.normalize())["평균"].transform("mean")
    daily_labor_min = out.groupby(out.index.normalize())["인건비"].transform("min")

    prod_zero_but_powered = (daily_prod == 0) & (daily_power >= 70)
    # (a) 인건비까지 손상된 날만 진짜 ERP 결측
    erp_missing = prod_zero_but_powered & (daily_labor_min == 1.5)
    # (b) 나머지는 증강 부작용
    aug_inconsistent = prod_zero_but_powered & (~erp_missing)

    out["is_erp_missing"] = erp_missing
    out["is_aug_inconsistent"] = aug_inconsistent
    log.append(("ERP측 결측", int(erp_missing.sum()), "is_erp_missing (평가·학습 모두 제외)"))
    log.append(
        ("증강 채널 불일치", int(aug_inconsistent.sum()), "is_aug_inconsistent (휴무로 분류, 한계로 기재)")
    )

    # 4개 구간을 과거값으로 대체하고 평균은 half-up 규칙으로 재구성한다.
    # 계측정지의 정답 자체는 대체값으로 평가하지 않고 마스크로 제외한다.
    for c in POWER_COLS:
        out.loc[outage, c] = np.nan
        out[c] = out[c].ffill()
    # half-up 반올림으로 평균 재구성 (비정지 구간에서는 원값과 100% 동일)
    out["평균"] = np.floor(out[POWER_COLS].mean(axis=1) + 0.5)

    # ── 기상·공장인원 결측 ──────────────────────────────────────────
    n_rain = int(out["강수량"].isna().sum())
    out["강수량"] = out["강수량"].fillna(0.0)  # 무강수로 해석
    log.append(("강수량 결측", n_rain, "0 으로 대체(무강수)"))

    for c in ("풍속", "공장인원"):
        n = int(out[c].isna().sum())
        out[c] = out[c].ffill()
        log.append((f"{c} 결측", n, "과거 유효값 전방대체(ffill), 선두 결측 유지"))

    log_df = pd.DataFrame(log, columns=["항목", "건수", "처리"])
    return out, log_df


# s01_diagnose.py::add_targets sha256=7cfa8a9d9702
def add_targets(df: pd.DataFrame) -> pd.DataFrame:
    """타깃 컬럼을 추가한다.

    `y_peak` 은 15분 단일 컬럼이 아니라 **4개 구간의 최대값**이다.
    이 정의에서만 보고서의 187/201/222 가 재현된다
    (`15분` 단독은 173.6/188/207 로 불일치).
    """
    out = df.copy()
    out["y_avg"] = out["평균"].astype(float)
    out["y_peak"] = out[POWER_COLS].max(axis=1).astype(float)
    return out


# s01_diagnose.py::build_operating_calendar sha256=a1227149f1dc
def build_operating_calendar(df: pd.DataFrame) -> pd.DataFrame:
    """일별 가동/휴무 캘린더를 데이터로 도출한다.

    `일생산량 합 == 0` 이면 휴무로 본다. 단 ERP 결측일은 생산량이 0이어도
    전력이 정상 가동 수준이므로 가동으로 분류한다.

    Returns
    -------
    pandas.DataFrame
        날짜 인덱스, 컬럼 `일생산량`/`일평균전력`/`요일`/`is_erp_missing`/`is_shutdown`/`레짐`.
    """
    day = df.index.normalize()
    cal = pd.DataFrame(
        {
            "일생산량": df.groupby(day)["생산량"].sum(),
            "일평균전력": df.groupby(day)["y_avg"].mean(),
            "is_erp_missing": df.groupby(day)["is_erp_missing"].any(),
            "is_aug_inconsistent": df.groupby(day)["is_aug_inconsistent"].any(),
        }
    )
    cal["요일"] = cal.index.dayofweek  # 0=월
    # 휴무 판정 — ERP 결측일은 제외
    cal["is_shutdown"] = (cal["일생산량"] == 0) & (~cal["is_erp_missing"])

    # 3레짐 — EDA에서 확인된 일평균전력 경계
    cal["레짐"] = pd.cut(
        cal["일평균전력"],
        bins=[-np.inf, 30, 70, np.inf],
        labels=["기저(셧다운)", "중간", "가동"],
    )

    # 연속 휴무 구간에 n일차 부여.
    # 그룹은 [가동일, 휴무, 휴무, ...] 형태라 cumcount 가 첫 휴무일에 1을 준다.
    # 다만 시계열 선두가 휴무로 시작하면(2021-01-01 신정) 그 그룹만 0에서 시작하므로 보정한다.
    grp = (~cal["is_shutdown"]).cumsum()
    nth = cal.groupby(grp).cumcount()
    first_is_shutdown = cal.groupby(grp)["is_shutdown"].transform("first").astype(int)
    cal["휴무_n일차"] = (nth + first_is_shutdown).where(cal["is_shutdown"], 0)
    # 휴무 직후 첫 가동일
    cal["is_재가동일"] = (~cal["is_shutdown"]) & cal["is_shutdown"].shift(1, fill_value=False)
    return cal


# s02_features.py::HOLIDAYS_2021 sha256=1010020cfcde
HOLIDAYS_2021 = pd.to_datetime([
    "2021-01-01",                               # 신정
    "2021-02-11", "2021-02-12", "2021-02-13",   # 설날 연휴
    "2021-03-01",                               # 삼일절
    "2021-05-05",                               # 어린이날
    "2021-05-19",                               # 부처님오신날
    "2021-06-06",                               # 현충일
    "2021-08-15", "2021-08-16",                 # 광복절 + 대체공휴일
])


# s02_features.py::FEATURE_LABELS sha256=8254b9c27455
FEATURE_LABELS: dict[str, str] = {}


# s02_features.py::_label sha256=d33a71235d9a
def _label(name: str, korean: str) -> str:
    """피처명에 한글 표시 라벨을 등록하고 원래 이름을 돌려준다."""
    FEATURE_LABELS[name] = korean
    return name


# s02_features.py::add_calendar_features sha256=dd5990705ff3
def add_calendar_features(d: pd.DataFrame, cal: pd.DataFrame, holidays=None) -> pd.DataFrame:
    """달력·공정상태 파생변수를 추가한다.

    달력은 기지 정보이며, 생산량으로 유도한 휴무 상태는 사전 운영계획을
    확보한다는 가정 아래 사용한다. 실제 생산실적과 계획의 차이는 검증되지 않았다.

    Parameters
    ----------
    d : pandas.DataFrame
        datetime 인덱스를 가진 시간별 데이터.
    cal : pandas.DataFrame
        1.4절에서 도출한 일별 가동 캘린더.
    holidays : array-like of datetime, optional
        공휴일 목록. 기본은 `HOLIDAYS_2021`(학습 구간). 서비스에서 2021-09-14 이후
        날짜를 예측할 때 운영 휴일표를 주입하는 통로다(노트북 결과에는 영향 없음).
    """
    out = d.copy()
    idx = out.index
    day = idx.normalize()
    hol = HOLIDAYS_2021 if holidays is None else pd.DatetimeIndex(holidays)

    # ── 시간정보 ──────────────────────────────────────────────────────
    out[_label("hour", "시간")] = idx.hour
    out[_label("dow", "요일")] = idx.dayofweek
    out[_label("month", "월")] = idx.month
    # 토·일을 분리한다 — 단일 '주말' 플래그로는 3레짐을 표현할 수 없다
    out[_label("is_sat", "토요일")] = (idx.dayofweek == 5).astype(int)
    out[_label("is_sun", "일요일")] = (idx.dayofweek == 6).astype(int)
    out[_label("is_holiday", "공휴일")] = day.isin(hol).astype(int)
    # 주기형 인코딩 — 23시와 0시가 인접함을 모델에 알려준다
    out[_label("hour_sin", "시간 sin")] = np.sin(2 * np.pi * idx.hour / 24)
    out[_label("hour_cos", "시간 cos")] = np.cos(2 * np.pi * idx.hour / 24)
    out[_label("dow_sin", "요일 sin")] = np.sin(2 * np.pi * idx.dayofweek / 7)
    out[_label("dow_cos", "요일 cos")] = np.cos(2 * np.pi * idx.dayofweek / 7)

    # ── 공정상태 ──────────────────────────────────────────────────────
    # 주간 = 인건비 1.0 구간(9~17시). 08시는 1.5 구간임에 유의.
    out[_label("is_daytime", "주간(9~17시)")] = idx.hour.isin(range(9, 18)).astype(int)
    # 동시 기동 시점 — 08시 피크율 24.5%(1위), 13시 17.1%
    out[_label("is_startup_08", "08시 기동")] = (idx.hour == 8).astype(int)
    out[_label("is_restart_13", "13시 재가동")] = (idx.hour == 13).astype(int)

    # 가동 캘린더 기반 (일 단위 → 시간 단위로 브로드캐스트)
    cal_h = cal.reindex(day)
    out[_label("is_shutdown", "휴무일")] = cal_h["is_shutdown"].to_numpy().astype(int)
    out[_label("shutdown_nth", "휴무 n일차")] = cal_h["휴무_n일차"].to_numpy().astype(int)
    out[_label("is_first_day_back", "휴무 직후 재가동일")] = cal_h["is_재가동일"].to_numpy().astype(int)
    # 전일이 휴무였는지 — 재가동 효과의 대리변수
    prev_shut = cal["is_shutdown"].shift(1, fill_value=False).reindex(day)
    out[_label("prev_day_shutdown", "전일 휴무")] = prev_shut.to_numpy().astype(int)
    # 가동 전환 = 전일과 가동상태가 바뀐 날
    switch = (cal["is_shutdown"] != cal["is_shutdown"].shift(1)).reindex(day)
    out[_label("is_state_switch", "가동 전환일")] = switch.fillna(False).to_numpy().astype(int)

    return out


# s02_features.py::SAFE_LAGS sha256=7c1a3aa136f3
SAFE_LAGS = (24, 48, 168)


# s02_features.py::build_origin_frame sha256=2f2a8dc9d87b
def build_origin_frame(d: pd.DataFrame, theta: float) -> pd.DataFrame:
    """일자 D 기준, **D일 24:00 시점에 관측이 완료된** 이동통계를 만든다.

    창의 오른쪽 끝을 `D일 23:00` 으로 두면 그 값은 D일 24:00 에 관측 완료되므로
    `origin(D+1) = D일 24:00` 에서 안전하게 사용할 수 있다.

    Returns
    -------
    pandas.DataFrame
        일자(D) 인덱스. 이 표를 `날짜 - 1일` 로 머지하면 D+1 의 피처가 된다.
    """
    avg, peak = d["y_avg"], d["y_peak"]
    is_peak = (peak >= theta).astype(float)

    cols = {}
    for win in (24, 168):
        # min_periods 를 창 크기와 같게 두어 부분 창(워밍업)을 배제한다
        cols[f"roll{win}_avg_mean"] = avg.rolling(win, min_periods=win).mean()
        cols[f"roll{win}_avg_max"] = avg.rolling(win, min_periods=win).max()
        cols[f"roll{win}_avg_std"] = avg.rolling(win, min_periods=win).std()
        cols[f"roll{win}_peak_max"] = peak.rolling(win, min_periods=win).max()
        cols[f"roll{win}_peak_cnt"] = is_peak.rolling(win, min_periods=win).sum()
    roll = pd.DataFrame(cols, index=d.index)

    # 각 날짜의 마지막 시각(23시) 행만 취한다 = 그 날 24:00 시점의 통계
    last = roll[roll.index.hour == 23].copy()
    last.index = last.index.normalize()
    last.index.name = "origin_date"

    for c in last.columns:
        FEATURE_LABELS.setdefault(
            c,
            c.replace("roll24_", "직전24h ")
            .replace("roll168_", "직전168h ")
            .replace("avg_mean", "평균전력 평균")
            .replace("avg_max", "평균전력 최대")
            .replace("avg_std", "평균전력 표준편차")
            .replace("peak_max", "peak15 최대")
            .replace("peak_cnt", "피크 발생건수"),
        )
    return last


# s02_features.py::add_lag_features sha256=d08d8888eb9a
def add_lag_features(d: pd.DataFrame) -> pd.DataFrame:
    """안전 lag(24·48·168시간)만 추가한다.

    `lag24` 의 참조 시각은 대상 시각보다 24시간 이르므로, 그 값의 **관측완료 시각**
    (참조시각 + 1시간)도 원점(= 대상일 00:00)보다 이르다. 따라서 안전하다.
    """
    out = d.copy()
    for col, kor in (("y_avg", "평균전력"), ("y_peak", "peak15")):
        for lag in SAFE_LAGS:
            name = _label(f"{col}_lag{lag}", f"{kor} {lag}시간 전")
            out[name] = out[col].shift(lag)
    return out


# s02_features.py::add_origin_stats sha256=1cbe5af9fe92
def add_origin_stats(d: pd.DataFrame, origin: pd.DataFrame) -> pd.DataFrame:
    """원점 기준 이동통계를 **대상일 24시간에 동일 값으로 브로드캐스트**한다.

    대상 시각 T 의 날짜에서 하루를 뺀 날(D)의 통계를 가져온다.
    같은 날 안에서는 값이 변하지 않으므로 `h>0` 누수가 원천적으로 불가능하다.
    """
    out = d.copy()
    key = out.index.normalize() - pd.Timedelta(days=1)
    merged = origin.reindex(key)
    for c in origin.columns:
        out[c] = merged[c].to_numpy()
    return out


# s02_features.py::add_production_weather_features sha256=b25a5b0e4870
def add_production_weather_features(d: pd.DataFrame) -> pd.DataFrame:
    """생산정보·기상정보 파생변수를 추가한다.

    생산량은 ERP **계획값**으로 가정하므로 대상 시점 값을 사용할 수 있다.
    이 가정의 타당성은 6.3절 '생산량 제외' ablation 으로 검증한다.
    """
    out = d.copy()
    out[_label("prod", "계획생산량")] = out["생산량"].astype(float)
    out[_label("headcount", "공장인원(정규화 공수)")] = out["공장인원"].astype(float)
    # 전일 동시각 대비 생산량 변화율 (분모 0 방지)
    prev = out["생산량"].shift(24)
    out[_label("prod_chg_ratio", "생산량 전일대비 변화율")] = (
        (out["생산량"] - prev) / prev.replace(0, np.nan)
    ).replace([np.inf, -np.inf], np.nan).fillna(0.0)
    # 당일 누적 생산량 — ERP 계획이므로 원점에서 기지
    out[_label("prod_cum_day", "일 누적생산량")] = out.groupby(out.index.normalize())["생산량"].cumsum()

    out[_label("temp", "기온")] = out["기온"].astype(float)
    out[_label("humid", "습도")] = out["습도"].astype(float)
    out[_label("wind", "풍속")] = out["풍속"].astype(float)
    out[_label("rain", "강수량")] = out["강수량"].astype(float)
    # 냉방도일·난방도일 — 기온의 비선형 효과를 선형 항으로 분해
    out[_label("cdd", "냉방도일 CDD")] = (out["기온"] - 24).clip(lower=0)
    out[_label("hdd", "난방도일 HDD")] = (18 - out["기온"]).clip(lower=0)
    return out


# s02_features.py::FEATURE_GROUPS sha256=f7da784d4c78
FEATURE_GROUPS = {
    "과거전력": [f"{c}_lag{l}" for c in ("y_avg", "y_peak") for l in SAFE_LAGS],
    "이동통계": [
        f"roll{w}_{s}"
        for w in (24, 168)
        for s in ("avg_mean", "avg_max", "avg_std", "peak_max", "peak_cnt")
    ],
    "시간정보": [
        "hour", "dow", "month", "is_sat", "is_sun", "is_holiday",
        "hour_sin", "hour_cos", "dow_sin", "dow_cos",
    ],
    "공정상태": [
        "is_daytime", "is_startup_08", "is_restart_13", "is_shutdown",
        "shutdown_nth", "is_first_day_back", "prev_day_shutdown", "is_state_switch",
    ],
    "생산정보": ["prod", "headcount", "prod_chg_ratio", "prod_cum_day"],
    "기상정보": ["temp", "humid", "wind", "rain", "cdd", "hdd"],
}


# s02_features.py::FEATURE_COLS sha256=c480027a000e
FEATURE_COLS = [c for cols in FEATURE_GROUPS.values() for c in cols]


# s02_features.py::build_features sha256=64369f22c609
def build_features(d: pd.DataFrame, cal: pd.DataFrame, theta: float, holidays=None) -> pd.DataFrame:
    """전체 피처 파이프라인. 누수 검증에서 재호출하므로 **순수 함수**로 둔다.

    Parameters
    ----------
    d : pandas.DataFrame
        1장에서 정비된 시간별 데이터.
    cal : pandas.DataFrame
        가동 캘린더.
    theta : float
        피크 정의 임계값(이동통계의 피크 발생건수에 사용).
    holidays : array-like of datetime, optional
        공휴일 목록. 기본 `HOLIDAYS_2021` (→ `add_calendar_features`).

    Returns
    -------
    pandas.DataFrame
        원본 + 파생변수. 워밍업 구간은 NaN 으로 남는다.
    """
    out = add_calendar_features(d, cal, holidays)
    out = add_lag_features(out)
    out = add_origin_stats(out, build_origin_frame(d, theta))
    out = add_production_weather_features(out)
    return out


# s10_package.py::bundle_predict sha256=c468a894cd9d
def bundle_predict(parts: dict, X: pd.DataFrame) -> dict:
    """모델 번들의 부스터로 예측한다.

    노트북의 재로드 검증과 서빙 패키지(`serving/_core.py`, 코드 생성)가 **같은 함수**를 쓴다.
    5.2절 레짐 모델의 `predict` 와 같은 규칙이다: 게이트가 레짐을 고르고, 그 레짐의
    회귀 모델이 예측하며, 학습에 없던 레짐으로 배정된 행은 fallback 이 채운다.

    Parameters
    ----------
    parts : dict
        `columns`(피처 순서), `gate`, `gate_features`, `classes`, `regs`({타깃: {레짐: 부스터}}),
        `fallbacks`({타깃: 부스터}), 선택적으로 `peak_clf`, `quantiles`({분위: 부스터}).
    X : pandas.DataFrame
        피처 행렬. 컬럼 순서와 dtype 은 여기서 강제한다.

    Returns
    -------
    dict[str, numpy.ndarray]
        `regime`, `y_avg`, `y_peak`, (있으면) `prob`, `q10`·`q50`·`q90`.
    """
    cols = list(parts["columns"])
    missing = [c for c in cols if c not in X.columns]
    if missing:
        raise KeyError(f"피처 누락: {missing[:5]}")
    # LightGBM 은 컬럼 순서가 바뀌어도 오류 없이 틀린 값을 낸다 → 계약 순서로 재정렬, float64 로 통일
    Xf = X.reindex(columns=cols).astype(np.float64)
    arr = Xf.to_numpy()

    gate_p = parts["gate"].predict(Xf[list(parts["gate_features"])].to_numpy())
    classes = np.asarray(parts["classes"])
    if gate_p.ndim == 1:
        # 2분류 게이트: sklearn predict 와 같다(p > 0.5 일 때만 두 번째 클래스)
        regime = classes[(gate_p > 0.5).astype(int)]
    else:
        regime = classes[np.argmax(gate_p, axis=1)]
    out = {"regime": regime.astype(int)}

    for tgt in ("y_avg", "y_peak"):
        pred = np.empty(len(Xf), float)
        assigned = np.zeros(len(Xf), bool)
        for r, bst in parts["regs"][tgt].items():
            m = regime == int(r)
            if m.any():
                pred[m] = bst.predict(arr[m])
                assigned |= m
        if (~assigned).any():
            pred[~assigned] = parts["fallbacks"][tgt].predict(arr[~assigned])
        out[tgt] = pred

    if parts.get("peak_clf") is not None:
        out["prob"] = parts["peak_clf"].predict(arr)
    for q, bst in (parts.get("quantiles") or {}).items():
        out[f"q{int(round(float(q) * 100))}"] = bst.predict(arr)
    return out


# s10_package.py::manifest_core_sha256 sha256=240d36783635
def manifest_core_sha256(manifest: dict) -> str:
    """매니페스트 자체의 무결성 해시.

    `bundle_id`·`manifest_sha256` 두 키를 뺀 나머지를 결정적 JSON(키 정렬·UTF-8·NaN 금지)으로
    직렬화한 sha256 이다. τ·구간 반폭처럼 매니페스트 안에만 있는 값의 변조를 잡는다.
    노트북 검증과 서빙 로더가 **같은 함수**로 계산한다(코드 생성).
    """
    core = {k: v for k, v in manifest.items() if k not in ("bundle_id", "manifest_sha256")}
    text = json.dumps(core, sort_keys=True, ensure_ascii=False, indent=1, allow_nan=False)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()
